name: Deploy to AWS EC2
on:
 push:
 branches:
 - main
jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout code
 uses: actions/checkout@v3
 - name: Set up SSH
 uses: webfactory/ssh-agent@v0.5.3
 with:
 ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
 - name: Copy files to EC2
 run: |
 ssh -o StrictHostKeyChecking=no ec2-user@<52.221.186.224>
"mkdir -p /home/ec2-user/apps"
 scp -o StrictHostKeyChecking=no -r ./app1 ./app2 ec2-
user@<52.221.186.224>:/home/ec2-user/apps
 - name: Restart Docker container on EC2
 run: |
 ssh -o StrictHostKeyChecking=no ec2-user@<52.221.186.224>
"docker stop app-container || true"
 ssh -o StrictHostKeyChecking=no ec2-user@<52.221.186.224>
"docker run -d -p 80:80 -v /home/ec2-user/apps:/usr/share/nginx/html
nginx"